ASITUS_THIRDPARTY_PRODUCT("vtk" "" "vtkAlgorithm.h" "vtkCommonCore-7.1")

if (3RDPARTY_vtk_INCLUDE_DIR STREQUAL "")
  message (STATUS "... VTK Include dir is not conventional")
  list (REMOVE_ITEM 3RDPARTY_NOT_INCLUDED 3RDPARTY_vtk_INCLUDE_DIR)
  set (3RDPARTY_vtk_INCLUDE_DIR ${3RDPARTY_vtk_DIR}/include/vtk-7.1 CACHE FILEPATH "Non-conventional inc dir" FORCE)
endif()

message (STATUS "... VTK Include dirs: ${3RDPARTY_vtk_INCLUDE_DIR}")
message (STATUS "... VTK Library dirs: ${3RDPARTY_vtk_LIBRARY_DIR}")
message (STATUS "... VTK Binary  dirs: ${3RDPARTY_vtk_DLL_DIR}")

string (REPLACE lib libd 3RDPARTY_vtk_LIBRARY_DIR_DEBUG ${3RDPARTY_vtk_LIBRARY_DIR})
if (3RDPARTY_vtk_LIBRARY_DIR_DEBUG AND EXISTS "${3RDPARTY_vtk_LIBRARY_DIR_DEBUG}")
  if (WIN32)
    if (NOT EXISTS "${3RDPARTY_vtk_LIBRARY_DIR_DEBUG}/vtkCommonCore-7.1.lib")
      set (3RDPARTY_vtk_LIBRARY_DIR_DEBUG "" CACHE INTERNAL FORCE)
    endif()
  else()
    if (NOT EXISTS "${3RDPARTY_vtk_LIBRARY_DIR_DEBUG}/libvtkCommonCore-7.1.so")
      set (3RDPARTY_vtk_LIBRARY_DIR_DEBUG "" CACHE INTERNAL FORCE)
    endif()
  endif()
endif()

if (WIN32)
  string (REPLACE bin bind 3RDPARTY_vtk_DLL_DIR_DEBUG ${3RDPARTY_vtk_DLL_DIR})
  if (3RDPARTY_vtk_DLL_DIR_DEBUG AND EXISTS "${3RDPARTY_vtk_DLL_DIR_DEBUG}")
    if (NOT EXISTS "${3RDPARTY_vtk_DLL_DIR_DEBUG}/vtkCommonCore-7.1.dll")
      set (3RDPARTY_vtk_DLL_DIR_DEBUG "" CACHE INTERNAL FORCE)
    endif()
  endif()
endif()

message (STATUS "... VTK Debug Library dirs: ${3RDPARTY_vtk_LIBRARY_DIR_DEBUG}")
message (STATUS "... VTK Debug Binary  dirs: ${3RDPARTY_vtk_DLL_DIR_DEBUG}")

#--------------------------------------------------------------------------
# Installation
if (WIN32)

  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkalglib-7.1.dll                      DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkChartsCore-7.1.dll                  DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkCommonComputationalGeometry-7.1.dll DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkCommonColor-7.1.dll                 DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkCommonCore-7.1.dll                  DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkCommonDataModel-7.1.dll             DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkCommonExecutionModel-7.1.dll        DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkCommonMath-7.1.dll                  DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkCommonMisc-7.1.dll                  DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkCommonSystem-7.1.dll                DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkCommonTransforms-7.1.dll            DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkFiltersCore-7.1.dll                 DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkFiltersExtraction-7.1.dll           DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkFiltersGeneral-7.1.dll              DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkFiltersGeometry-7.1.dll             DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkFiltersHybrid-7.1.dll               DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkFiltersImaging-7.1.dll              DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkFiltersModeling-7.1.dll             DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkFiltersParallel-7.1.dll             DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkFiltersSources-7.1.dll              DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkFiltersStatistics-7.1.dll           DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkfreetype-7.1.dll                    DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkGUISupportQt-7.1.dll                DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkglew-7.1.dll                        DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkImagingColor-7.1.dll                DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkImagingCore-7.1.dll                 DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkImagingFourier-7.1.dll              DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkImagingGeneral-7.1.dll              DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkImagingHybrid-7.1.dll               DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkImagingSources-7.1.dll              DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkInteractionWidgets-7.1.dll          DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkInteractionStyle-7.1.dll            DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkInfovisCore-7.1.dll                 DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkInfovisLayout-7.1.dll               DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkIOCore-7.1.dll                      DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkIOLegacy-7.1.dll                    DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkParallelCore-7.1.dll                DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkRenderingAnnotation-7.1.dll         DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkRenderingContext2D-7.1.dll          DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkRenderingContextOpenGL2-7.1.dll     DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkRenderingCore-7.1.dll               DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkRenderingFreeType-7.1.dll           DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkRenderingLabel-7.1.dll              DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkRenderingOpenGL2-7.1.dll            DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkRenderingVolume-7.1.dll             DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtksys-7.1.dll                         DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkViewsContext2D-7.1.dll              DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkViewsCore-7.1.dll                   DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkViewsInfovis-7.1.dll                DESTINATION bin)
  install (FILES ${3RDPARTY_vtk_DLL_DIR}/vtkzlib-7.1.dll                        DESTINATION bin)

endif()
