ASITUS_THIRDPARTY_PRODUCT("vtk" "" "vtkAlgorithm.h" "vtkCommonCore-8.2")

if (3RDPARTY_vtk_INCLUDE_DIR STREQUAL "")
  message (STATUS "... VTK Include dir is not conventional")
  list (REMOVE_ITEM 3RDPARTY_NOT_INCLUDED 3RDPARTY_vtk_INCLUDE_DIR)
  set (3RDPARTY_vtk_INCLUDE_DIR ${3RDPARTY_vtk_DIR}/include/vtk-8.2 CACHE FILEPATH "Non-conventional inc dir" FORCE)
endif()

message (STATUS "... VTK Include dirs: ${3RDPARTY_vtk_INCLUDE_DIR}")
message (STATUS "... VTK Library dirs: ${3RDPARTY_vtk_LIBRARY_DIR}")
message (STATUS "... VTK Binary  dirs: ${3RDPARTY_vtk_DLL_DIR}")

string (REPLACE lib libd 3RDPARTY_vtk_LIBRARY_DIR_DEBUG ${3RDPARTY_vtk_LIBRARY_DIR})
if (3RDPARTY_vtk_LIBRARY_DIR_DEBUG AND EXISTS "${3RDPARTY_vtk_LIBRARY_DIR_DEBUG}")
  if (WIN32)
    if (NOT EXISTS "${3RDPARTY_vtk_LIBRARY_DIR_DEBUG}/vtkCommonCore-8.2.lib")
      set (3RDPARTY_vtk_LIBRARY_DIR_DEBUG "" CACHE INTERNAL FORCE)
    endif()
  else()
    if (NOT EXISTS "${3RDPARTY_vtk_LIBRARY_DIR_DEBUG}/libvtkCommonCore-8.2.so")
      set (3RDPARTY_vtk_LIBRARY_DIR_DEBUG "" CACHE INTERNAL FORCE)
    endif()
  endif()
endif()

if (WIN32)
  string (REPLACE bin bind 3RDPARTY_vtk_DLL_DIR_DEBUG ${3RDPARTY_vtk_DLL_DIR})
  if (3RDPARTY_vtk_DLL_DIR_DEBUG AND EXISTS "${3RDPARTY_vtk_DLL_DIR_DEBUG}")
    if (NOT EXISTS "${3RDPARTY_vtk_DLL_DIR_DEBUG}/vtkCommonCore-8.2.dll")
      set (3RDPARTY_vtk_DLL_DIR_DEBUG "" CACHE INTERNAL FORCE)
    endif()
  endif()
endif()

message (STATUS "... VTK Debug Library dirs: ${3RDPARTY_vtk_LIBRARY_DIR_DEBUG}")
message (STATUS "... VTK Debug Binary  dirs: ${3RDPARTY_vtk_DLL_DIR_DEBUG}")

#--------------------------------------------------------------------------
# Installation
#--------------------------------------------------------------------------

if (WIN32)
  set (3RDPATY_INSTALL_DIR ${3RDPARTY_vtk_DLL_DIR})
  set (LIB_PREFIX "")
  set (LIB_SUFFIX ".dll")
else()
  set (3RDPATY_INSTALL_DIR ${3RDPARTY_vtk_LIBRARY_DIR})
  set (LIB_PREFIX "lib")
  set (LIB_SUFFIX ".so.1")
endif()

install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkChartsCore-8.2${LIB_SUFFIX}                  DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkCommonComputationalGeometry-8.2${LIB_SUFFIX} DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkCommonColor-8.2${LIB_SUFFIX}                 DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkCommonCore-8.2${LIB_SUFFIX}                  DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkCommonDataModel-8.2${LIB_SUFFIX}             DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkCommonExecutionModel-8.2${LIB_SUFFIX}        DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkCommonMath-8.2${LIB_SUFFIX}                  DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkCommonMisc-8.2${LIB_SUFFIX}                  DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkCommonSystem-8.2${LIB_SUFFIX}                DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkCommonTransforms-8.2${LIB_SUFFIX}            DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkFiltersCore-8.2${LIB_SUFFIX}                 DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkFiltersExtraction-8.2${LIB_SUFFIX}           DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkFiltersGeneral-8.2${LIB_SUFFIX}              DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkFiltersGeometry-8.2${LIB_SUFFIX}             DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkFiltersHybrid-8.2${LIB_SUFFIX}               DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkFiltersImaging-8.2${LIB_SUFFIX}              DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkFiltersModeling-8.2${LIB_SUFFIX}             DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkFiltersParallel-8.2${LIB_SUFFIX}             DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkFiltersSources-8.2${LIB_SUFFIX}              DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkFiltersStatistics-8.2${LIB_SUFFIX}           DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkfreetype-8.2${LIB_SUFFIX}                    DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkGUISupportQt-8.2${LIB_SUFFIX}                DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkglew-8.2${LIB_SUFFIX}                        DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkImagingColor-8.2${LIB_SUFFIX}                DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkImagingCore-8.2${LIB_SUFFIX}                 DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkImagingFourier-8.2${LIB_SUFFIX}              DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkImagingGeneral-8.2${LIB_SUFFIX}              DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkImagingHybrid-8.2${LIB_SUFFIX}               DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkImagingSources-8.2${LIB_SUFFIX}              DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkInteractionWidgets-8.2${LIB_SUFFIX}          DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkInteractionStyle-8.2${LIB_SUFFIX}            DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkInfovisCore-8.2${LIB_SUFFIX}                 DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkInfovisLayout-8.2${LIB_SUFFIX}               DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkIOCore-8.2${LIB_SUFFIX}                      DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkIOImage-8.2${LIB_SUFFIX}                     DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkIOLegacy-8.2${LIB_SUFFIX}                    DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkIOExport-8.2${LIB_SUFFIX}                    DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkIOXML-8.2${LIB_SUFFIX}                       DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkIOXMLParser-8.2${LIB_SUFFIX}                 DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkexpat-8.2${LIB_SUFFIX}                       DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkIOExportOpenGL2-8.2${LIB_SUFFIX}             DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkParallelCore-8.2${LIB_SUFFIX}                DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkRenderingAnnotation-8.2${LIB_SUFFIX}         DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkRenderingContext2D-8.2${LIB_SUFFIX}          DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkRenderingContextOpenGL2-8.2${LIB_SUFFIX}     DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkRenderingCore-8.2${LIB_SUFFIX}               DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkRenderingGL2PSOpenGL2-8.2${LIB_SUFFIX}       DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkRenderingFreeType-8.2${LIB_SUFFIX}           DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkRenderingLabel-8.2${LIB_SUFFIX}              DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkRenderingOpenGL2-8.2${LIB_SUFFIX}            DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkRenderingVolume-8.2${LIB_SUFFIX}             DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtksys-8.2${LIB_SUFFIX}                         DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkViewsContext2D-8.2${LIB_SUFFIX}              DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkViewsCore-8.2${LIB_SUFFIX}                   DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkViewsInfovis-8.2${LIB_SUFFIX}                DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkzlib-8.2${LIB_SUFFIX}                        DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtklz4-8.2${LIB_SUFFIX}                         DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkgl2ps-8.2${LIB_SUFFIX}                       DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkpng-8.2${LIB_SUFFIX}                         DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtklibharu-8.2${LIB_SUFFIX}                     DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkDICOMParser-8.2${LIB_SUFFIX}                 DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkmetaio-8.2${LIB_SUFFIX}                      DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtktiff-8.2${LIB_SUFFIX}                        DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkjpeg-8.2${LIB_SUFFIX}                        DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtklzma-8.2${LIB_SUFFIX}                        DESTINATION bin)
install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkdoubleconversion-8.2${LIB_SUFFIX}            DESTINATION bin)
